version: '3.1'
services:
  db-veiculos:
    image: postgres:11
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=travel
      - POSTGRES_PASSWORD=travel
      - POSTGRES_DB=travel-backend