name: deploy-database

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        required: true
        default: 'dev'
      ENV_VERSION:
        description: 'Environment version'
        required: true
        default: 'v1'

jobs:
  deploy-database:
    env:
      PROJECT_NAME: travels-backend
      AWS_REGION: us-east-1
      REMOTE_STATE_BUCKET: rocketseat-remote-state
      REMOTE_STATE_FILE: travels-backend-database.tfstate
      REMOTE_STATE_AWS_REGION: us-east-1
      PRODUCT: rocketseat
      CREATED_BY: devops-tools
      OWNER: squad-rocketseat
      ENV: ${{ github.event.inputs.ENV }}
      ENV_VERSION: ${{ github.event.inputs.ENV_VERSION }}
      ROLE: db
      ENGINE: aurora-postgresql
      ENGINE_VERSION: 10.7
      DATABASE_NAME: travels
      DATABASE_USERNAME: travels
      BACKUP_RETENTION_PERIOD: 5
      STORAGE_ENCRYPTED: true
      DELETION_PROTECTION: false
      ENGINE_MODE: serverless
      SKIP_FINAL_SNAPSHOT: true
      COPY_TAGS_TO_SNAPSHOT: true
      AUTO_PAUSE: true
      MAX_CAPACITY: 8
      MIN_CAPACITY: 2
      SECONDS_UNTIL_AUTO_PAUSE: 300
      TIMEOUT_ACTION: ForceApplyCapacityChange
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure-crentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_RDS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_RDS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      run: chmod +x ./devops/scripts/deploy-database.sh && ./devops/scripts/deploy-database.sh